common: define BT_DIAG_IGNORE_UNUSED_BUT_SET_VARIABLE for gcc
GCC 16 brings changes to the `-Wunused-but-set-*` warnings [1], making
it flag more cases.

    Since GCC 16, -Wunused-but-set-* warning options have been extended
    to have multiple levels controlling what kinds of uses disable the
    warnings for variables which are otherwise unused. Older versions of
    GCC only implemented what has become -Wunused-but-set-variable=1 or
    -Wunused-but-set-parameter=1, while the new default for
    -Wunused-but-set-variable or -Wunused-but-set-parameter is =3 (the
    new defaults are also used when these warnings are enabled by -Wall
    or -Wextra, respectively). =2 ignores pre/post inc/decrements on the
    variable, =3 also ignores compound assignments if the LHS variable
    is not also used on the RHS.

It therefore now flags this:

      CXX      plugins/ctf/common/src/metadata/tsdl/metadata_libctf_parser_la-parser.lo
    plugins/ctf/common/src/metadata/tsdl/parser.cpp: In function 'int yyparse(ctf_scanner*, yyscan_t)':
    plugins/ctf/common/src/metadata/tsdl/parser.cpp:3101:9: error: variable 'yynerrs' set but not used [-Werror=unused-but-set-variable=]
     3101 |     int yynerrs = 0;
          |         ^~~~~~~

Clang already reported this, which is why we have a
`BT_DIAG_IGNORE_UNUSED_BUT_SET_VARIABLE` at the top of the file.  Fix it
by also defining `BT_DIAG_IGNORE_UNUSED_BUT_SET_VARIABLE` for gcc.

No version check is needed since gcc has had `-Wunused-but-set-variable`
for basically forever (gcc 4.8 has it).

[1] https://gcc.gnu.org/gcc-16/porting_to.html

Change-Id: I7f8662ed2997a87c77757f3ba43912b75d531561
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/17671
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>
Tested-by: jenkins <jenkins@lttng.org>