Include Python.h first
When building against glibc 2.43, I get:

      CC       python-plugin-provider/babeltrace2_python_plugin_provider_la-python-plugin-provider.lo
    sdIn file included from /usr/include/python3.14/Python.h:14,
                     from /home/smarchi/src/babeltrace/src/py-common/py-common.h:13,
                     from /home/smarchi/src/babeltrace/src/python-plugin-provider/python-plugin-provider.c:21:
    /usr/include/python3.14/pyconfig.h:2007:9: error: '_POSIX_C_SOURCE' redefined [-Werror]
     2007 | #define _POSIX_C_SOURCE 200809L
          |         ^~~~~~~~~~~~~~~
    In file included from /usr/include/errno.h:25,
                     from /home/smarchi/src/babeltrace/src/logging/log.h:15,
                     from /home/smarchi/src/babeltrace/src/lib/logging.h:18,
                     from /home/smarchi/src/babeltrace/src/python-plugin-provider/python-plugin-provider.c:10:
    /usr/include/features.h:319:10: note: this is the location of the previous definition
      319 | # define _POSIX_C_SOURCE        202405L
          |          ^~~~~~~~~~~~~~~

This is the glibc commit that likely introduced this regression:

https://gitlab.com/gnutools/glibc/-/commit/a5cc3018f31a125f019685b239c6e5a0bf1a272b

What happens is:

 - Python's pyconfig.h unconditionally defines _POSIX_C_SOURCE to
   200809L.  Any code interfacing with the Python C API must be compiled
   with the same pre-processor definitions that influence the standard
   library that Python itself was compiled with, presumably for ABI
   reasons.

 - glibc defines _POSIX_C_SOURCE to some default value, if no other
   *_SOURCE macro was defined earlier.  Before 2.43, it used 200809L, so
   Python and glibc agreed.  But starting with 2.43, it uses 202405L,
   hence the disagreement.

The Python doc actually says [1]:

    Note: Since Python may define some pre-processor definitions which
    affect the standard headers on some systems, you must include
    Python.h before any standard headers are included.

It sucks, but that's the way it is.

Change all the includes of Python.h, py-common.h and py-common.hpp to
appear as early as possible, where they are included, ensuring that
Python.h will always be included before any system header.

Adjust .clang-format so that it will keep the Python includes first.

[1] https://docs.python.org/3/c-api/intro.html#include-files

Change-Id: I530ab5dc27f2701352bc6c9a2c2a8b98c9dd1b40
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/16644
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>