tests: fix non-UTF-8 output from `test-uuid` breaking pytest capture
I noticed that running "make check" would fail certain tests like this
(not putting the whole backtrace because it's irrelevant):

      File "/usr/lib/python3.14/site-packages/_pytest/capture.py", line 209, in getvalue
        return self.buffer.getvalue().decode("UTF-8")
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 736: invalid continuation byte

This is due to these tests emitting non-UTF-8 data,  and "make check"
passing `--capture=tee-sys` to pytest.  It can be reproduced like this:

    $ ( source /home/simark/build/babeltrace/tests/utils/env.sh
        bt-python-env python -m pytest --capture=tee-sys tests/cpp-common/test-uuid.cpp::test_subscript_operator_of_bt2c_uuid_returns_expected_bytes )

This ends up calling the Catch2 tests like this:

    $ /home/simark/build/babeltrace/tests/cpp-common/test-uuid 'Subscript operator of `bt2c::Uuid` returns expected bytes' -s

With `-s`, Catch2 prints what the test macro was passed, and some of
these contain raw test data bytes:

    /home/simark/src/babeltrace/tests/cpp-common/test-uuid.cpp:56: PASSED:
      CHECK( _mUuid[0] == 0xc2 )
    with expansion:
      '...' == 194

where `...` is garbage due to the literal byte 0xfe being output.

pytest's capture machinery apparently expects the output of the
subprocess to be valid UTF-8 (which seems reasonable to me in this day
and age).  Outputting raw bytes in the terminal is probably not a good
idea anyway, as it can have unexpected effects on the terminal
configuration.

This went unnoticed because the CI runs pytest directly, not "make
check".

The problem happens when Catch2 tries to stringify some `std::uint8_t`
values.  The backtrace where this happens is:

    (gdb) bt
    #0  Catch::StringMaker<signed char, void>::convert[abi:cxx11](signed char) (value=-62 '\302') at src/catch2/catch_tostring.cpp:259
    #1  0x00005555556e7569 in Catch::Detail::stringify<signed char> (e=<optimized out>) at src/catch2/../catch2/catch_tostring.hpp:147
    #2  Catch::StringMaker<char, void>::convert[abi:cxx11](char) (c=<optimized out>) at src/catch2/catch_tostring.cpp:276
    #3  Catch::Detail::stringify<char> (e=<optimized out>) at src/catch2/../catch2/catch_tostring.hpp:147
    #4  Catch::StringMaker<unsigned char, void>::convert[abi:cxx11](unsigned char) (value=<optimized out>) at src/catch2/catch_tostring.cpp:279
    #5  0x00005555556a6234 in Catch::Detail::stringify<unsigned char> (e=@0x7bfff49f242a: 194 '\302') at /usr/include/catch2/catch_tostring.hpp:147
    #6  0x00005555556a521c in Catch::BinaryExpr<unsigned char, int>::streamReconstructedExpression (this=0x7bfff49f2420, os=...) at /usr/include/catch2/internal/catch_decomposer.hpp:203
    #7  0x000055555570b916 in Catch::operator<< (out=..., expr=...) at src/catch2/../catch2/internal/catch_decomposer.hpp:188
    #8  Catch::operator<< (os=..., lazyExpr=...) at src/catch2/internal/catch_lazy_expr.cpp:22
    #9  0x00005555556cfed6 in Catch::ReusableStringStream::operator<< <Catch::LazyExpression> (this=0x7fffffffc260, value=...) at src/catch2/../catch2/internal/catch_reusable_string_stream.hpp:46
    #10 Catch::AssertionResultData::reconstructExpression[abi:cxx11]() const (this=this@entry=0x7fffffffc548) at src/catch2/catch_assertion_result.cpp:23
    #11 0x00005555556d0721 in Catch::AssertionResult::getExpandedExpression[abi:cxx11]() const (this=this@entry=0x7fffffffc510) at src/catch2/catch_assertion_result.cpp:88
    #12 0x00005555556d082d in Catch::AssertionResult::hasExpandedExpression (this=this@entry=0x7fffffffc510) at src/catch2/catch_assertion_result.cpp:84
    #13 0x00005555556ab63a in Catch::(anonymous namespace)::ConsoleAssertionPrinter::printReconstructedExpression (this=0x7fffffffc3f0) at src/catch2/reporters/catch_reporter_console.cpp:162
    #14 Catch::(anonymous namespace)::ConsoleAssertionPrinter::print (this=0x7fffffffc3f0) at src/catch2/reporters/catch_reporter_console.cpp:142
    #15 Catch::ConsoleReporter::assertionEnded (this=this@entry=0x7cdff57e0040, _assertionStats=...) at src/catch2/reporters/catch_reporter_console.cpp:435

Notice how frame #4 is for `unsigned char`, frame #3 is for `char`, and
frame #1 is for  `signed char`.  The unsigned char value 0xc2 becomes
interpreted as the negative value -62 when passed down.

For such a value, the conversion code for `signed char` [1] does:

        char chstr[] = "' '";
        chstr[1] = value;
        return chstr;

which ends up printing the byte 0xc2.  I don't know if it's a bug in
Catch2 or not.

The workaround done in this patch is to cast those values to int before
comparing them.  Add a `intFromByte` function in
`tests/utils/common.hpp` and use it.

The same issue happens with `bt2c::Uuid` and `bt2c::UuidView`, which
Catch2 considers a sequence of `std::uint8_t` (and therefore prints each
elements individually).  Fix this one by defining operator<< functions
for `UuidView` and `Uuid`.  This makes the output like:

    /home/simark/src/babeltrace/tests/cpp-common/test-uuid.cpp:241: PASSED:
      CHECK( view == _mUuidView )
    with expansion:
      UuidView {c2281e4a-699b-4b78-903f-2f8407fe2b77}
      ==
      UuidView {c2281e4a-699b-4b78-903f-2f8407fe2b77}

    /home/simark/src/babeltrace/tests/cpp-common/test-uuid.cpp:256: PASSED:
      CHECK( bt2c::Uuid {bytes} == _mUuid )
    with expansion:
      Uuid {c2281e4a-699b-4b78-903f-2f8407fe2b77}
      ==
      Uuid {c2281e4a-699b-4b78-903f-2f8407fe2b77}

I chose to print the type name so that it can be easily told apart from
the UUID string tests.

Finally, change the pytest Catch2 runner code to always expect UTF-8
from the subprocesses (both stdout and stderr).  This will make any
similar problem apparent to anybody running pytest directly.

This is done by always running subprocesses with `encoding="utf-8"`,
which implies text mode.  If a subprocess emits some non-UTF-8 output,
we'll get some `UnicodeDecodeError` to point it out.  Change
`_Catch2TestItem.runtest()` to write to the text stream `sys.stdout`
instead of to the byte stream `sys.stdout.buffer`.

[1] https://github.com/catchorg/Catch2/blob/bcfb10e498df3e2ed8f814b3e4b689b9a85608ab/src/catch2/catch_tostring.cpp#L258-L274

Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Change-Id: I7a0892160521fa725a9488fafb5519fe9aff51a2
Reviewed-on: https://review.lttng.org/c/babeltrace/+/18199
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>
Tested-by: jenkins <jenkins@lttng.org>