tests/utils: move vendored catch2
When building on Arch Linux, with package catch2 3.13.0-1 installed, I
get this:

      CXXLD    bitfield/test-bitfield
    /usr/bin/ld: bitfield/test-bitfield.o: in function `bool check_result_impl<unsigned int, unsigned long long, unsigned char>(unsigned int, unsigned long long, unsigned char*, char const*, unsigned int, unsigned int, char const*) [clone .constprop.0] [clone .isra.0]':
    /home/simark/src/babeltrace/tests/bitfield/test-bitfield.cpp:133:(.text+0x3ef): undefined reference to `Catch::Capturer::Capturer(Catch::StringRef, Catch::SourceLineInfo const&, Catch::ResultWas::OfType, Catch::StringRef)'

The problem is that because of the `-I$(top_srcdir)/tests/utils` flag,
we always include the headers from the vendored catch2, even when we
want to use catch2 from the system.  Apparently, the types in the
vendored headers don't match the types in the system library.

Fix this by moving the vendored catch2 one level down, and only adding
the appropriate `-I` to find it when `--enable-vendor-catch2` is used.

Change-Id: I8189c079f4b05ad2a69b47614062233b07c9b420
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/16857
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>