Include Python.h first
Fixes:

      CC       py-common.lo
    In file included from /usr/include/python3.14/Python.h:14,
                     from /home/simark/src/babeltrace/src/py-common/py-common.c:31:
    /usr/include/python3.14/pyconfig.h:2007:9: error: '_POSIX_C_SOURCE' redefined [-Werror]
     2007 | #define _POSIX_C_SOURCE 200809L
          |         ^~~~~~~~~~~~~~~
    In file included from /usr/include/errno.h:25,
                     from /home/simark/src/babeltrace/src/logging/log.h:12,
                     from /home/simark/src/babeltrace/src/py-common/py-common.c:27:
    /usr/include/features.h:319:10: note: this is the location of the previous definition
      319 | # define _POSIX_C_SOURCE        202405L
          |          ^~~~~~~~~~~~~~~

See commit af07d58f7790 ("Include Python.h first") on the master branch
for more details.

Change-Id: I6541e53389fc5e0d334888993001fc4f3ae083b2
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/16666
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>