cli: fix uninitialized variable error
Fix:

      CC       babeltrace2.o
    /home/smarchi/src/babeltrace/src/cli/babeltrace2.c:1017:56: error: variable 'trace_fmt' is uninitialized when used here [-Werror,-Wuninitialized]
     1017 |                         fprintf(out_stream, "unknown trace format [`%s`])", trace_fmt);
          |                                                                             ^~~~~~~~~
    /home/smarchi/src/babeltrace/src/cli/babeltrace2.c:1010:24: note: initialize the variable 'trace_fmt' to silence this warning
     1010 |                 const char *trace_fmt;
          |                                      ^
          |                                       = NULL

Looks like a simple mistake, the fprintf should use `text`.

Likely introduced by 4f8c4505abc2 ("cli: show trace format when printing
LTTng live sessions").

Change-Id: I3d660241d4086a0690823815a21fcc6f27701d13
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/16645
Tested-by: jenkins <jenkins@lttng.org>
Reviewed-by: Philippe Proulx <eeppeliteloop@gmail.com>