python: remove F811 ignores
These are now unnecessary.  In abe2ca1601e ("bt2: define overloads of `Graph.add_component()`"), I wrote:

    The `noqa: F811` comments are necessary to avoid the following flake8
    warnings:

        $ flake8
        ./src/bindings/python/bt2/bt2/graph.py:74:5: F811 redefinition of unused 'add_component' from line 60
        ./src/bindings/python/bt2/bt2/graph.py:88:5: F811 redefinition of unused 'add_component' from line 74
        ./src/bindings/python/bt2/bt2/graph.py:101:5: F811 redefinition of unused 'add_component' from line 88

    I believe this is due to our typing module hack resulting in flake8 not
    recognizing `typing.overload`: I don't get these warnings when using
    `import typing` at the top of the file, rather than our hack.  So in the
    distant future, when we can use the built-in typing module directly, we
    can remove these comments.

We don't use the local typing module anymore, and in any case, flake8 no
longer reports errors for these now.

Change-Id: I3d9ac6e60adf5b51ed15b9d68dd8fb34550019a5
Signed-off-by: Simon Marchi <simon.marchi@efficios.com>
Reviewed-on: https://review.lttng.org/c/babeltrace/+/18317